---
- name: Instala el firewall (UFW)
  apt:
    name: ufw
    state: present
    
- name: Configura el firewall (UFW)    
  ufw:
    direction: "{{ item.direction }}"
    policy:  "{{ item.policy }}"
  with_items:
    - { direction: 'outgoing', policy: 'allow' }   
    - { direction: 'incoming', policy: 'deny' }

- name: Configura regla para ssh
  ufw:
    rule: allow
    name: OpenSSH  
  notify: reiniciar ufw
  
- name: Activar ufw
  ufw: 
    state: enabled 